# Generated by Django 5.2.7 on 2025-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=225)),
                ('autor', models.CharField(max_length=225)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
