# Generated by Django 5.2.7 on 2025-10-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
